# Food Delivery Data Exploration and Analysis 4

## Agenda

- Spliting & Stacking
- Introduction to Pandas
- Pandas Core Components - DataFrame & Series
- Zomato Dataset loading & inspection.
- Basic Operations in rows & Columns

# Split

## <span style="color: skyblue;"> Parameters for Splitting Arrays </span>

Splitting is an important concept, especially in machine learning workflows.

### Real world intuition

When building a machine learning model, we should not train and test on the same data. Instead:

* Split data into Training data and Testing data
* Train the model on partial data
* Keep some data unseen
* Test the model on unseen data — this helps validate model performance

<span style="color: red;"> Important:</span>
* Without splitting, we cannot properly judge whether a model is good or not

<span style="color: orange;">Doubt by Learner:</span>
* Why can we not use full data for both training and testing?
* What happens if we do not split the dataset?

All splitting functions take the following parameters:

1. array: The array to be split.
2. indices_or_sections:
   - If an integer `N`, the array is split into `N` equal sections.
   - If a list of indices, the splits happen at those positions.

## <span style="color: skyblue;"> Splitting Arrays with np.split() </span>

`np.split()` splits an array into sections along a specified axis:
- **axis=0**: Split rows.
- **axis=1**: Split columns (for 2D arrays).


**Example 1: Splitting a 1D Array**

In [ ]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 sections
split_1d = np.split(array_1d, 3)

print("Original Array:", array_1d)
print("Splits:", split_1d)

Original Array: [1 2 3 4 5 6]
Splits: [array([1, 2]), array([3, 4]), array([5, 6])]

**Prerequisites for Splitting**

- The total number of elements **must be divisible** by the number of splits.
- For 2D arrays, ensure the axis matches the shape of the array.

**Example**:
- A 1D array with 6 elements can be split into 2 or 3 equal parts, but **not 4**.
- A 2D array with 4 columns can be split horizontally into 2 parts, but **not 3**.

In [ ]:
# This is expected to fail!
split_1d = np.split(array_1d, 4)

ValueError: array split does not result in an equal division

**Example 2: Splitting a 2D Array**

In [ ]:
# 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])

# Split into 2 along axis=1 (columns)
split_2d = np.split(array_2d, 2, axis=1)

print("Original Array:\n", array_2d)
print("=="*10)
print("Splits:")
for part in split_2d:
    print(part)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
====================
Splits:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]

**Explanation:**
- **1D Array**: Split into 3 equal parts.
- **2D Array**: Split columns into 2 equal sections using `axis=1`.

<span style="background-color: red;color: White;">**[Ask Learners]:**</span>

<span style="color: violet;">What is the difference between splitting along axis 0 and axis 1?</span>

### Business Context

In Zomato analytics, np.split() allows efficient partitioning of datasets by restaurants, cuisines, or metrics. This supports training predictive models, segment-level analysis, and parallel processing, enabling faster, consistent, and actionable business insights.

## <span style="color: skyblue;"> Horizontal Splitting with np.hsplit() </span>

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/330/original/hvsp1.png?1764924592" width="500" />

`np.hsplit()` splits a 2D array horizontally into sections (columns).

>**Shortcut:** Equivalent to np.split(array, N, axis=1).

**Example: Horizontal Splitting**

In [ ]:
# Horizontal split
hsplit_2d = np.hsplit(array_2d, 2)

print("Original Array:\n", array_2d)
print("=="*10)
print("Horizontal Splits:")
for part in hsplit_2d:
    print(part)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
====================
Horizontal Splits:
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]

**Explanation:**
- `np.hsplit()`  divides the columns into equal sections.
- This is a convenient method for column-wise splitting.


## <span style="color: skyblue;"> Vertical Splitting with np.vsplit() </span>

`np.vsplit()` splits a 2D array vertically into sections (rows).

>**Shortcut:** Equivalent to np.split(array, N, axis=0).

**Example: Vertical Splitting**

In [ ]:
# Vertical split
vsplit_2d = np.vsplit(array_2d, 2)

print("Original Array:\n", array_2d)
print("Vertical Splits:")
for part in vsplit_2d:
    print(part)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Vertical Splits:
[[1 2 3 4]]
[[5 6 7 8]]

**Explanation:**
* `np.vsplit()` divides rows into equal sections.
* This is a convenient method for row-wise splitting.

## <span style="color: skyblue;"> Custom Splits with Indices </span>

Instead of dividing into equal parts, we can use indices for custom splits.

In [ ]:
# Split using indices
custom_split = np.split(array_1d, [2, 5])

print("Original Array:", array_1d)
print("Custom Splits:", custom_split)

Original Array: [1 2 3 4 5 6]
Custom Splits: [array([1, 2]), array([3, 4, 5]), array([6])]

**Explanation:**
- Splits occur at positions `[2, 5]`, creating 3 parts:
  - `[1, 2]`
  - `[3, 4, 5]`
  - `[6]`.

<span style="color: red;"> Note:</span>
* This is based on index positions, not actual values
* It is less commonly used, but learners should be aware of it

### Business Context

In Zomato analytics, horizontal, vertical, and custom array splits enable targeted analysis of features and restaurant segments. This supports efficient processing of large datasets, driving precise insights for pricing strategies, promotions, and feature-level decision-making.

# Question
What will be the output?

# Choices
- [x] `[array([[1], [3], [5]]), array([[2], [4], [6]])]`
- [ ] `[array([[1, 2]]), array([[3, 4], [5, 6]])]`
- [ ] `[array([1, 3, 5]), array([2, 4, 6])]`
- [ ] Error

## <span style="color: skyblue;"> Stacking in NumPy </span>

Stacking is the opposite of splitting — instead of dividing arrays, we combine them.

## <span style="color: skyblue;"> Vertical Stacking with np.vstack() </span>

`np.vstack()` stacks arrays along the vertical axis (rows).
* All arrays must have the same number of columns for vertical stacking.

> **[Interactive]:** Watch vstack and hstack combine arrays visually:  
> [Stacking Visualizer](https://aiml-v-izs.vercel.app/v/fd-z1y6t8h5/stacking?embed=1)

**Example: Vertical Stacking**

In [ ]:
import numpy as np

# Define arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack vertically
vstack_result = np.vstack([array1, array2])

print("Array 1:", array1)
print("Array 2:", array2)
print("Vertical Stack:\n", vstack_result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]

**Explanation:**
- The arrays `[1, 2, 3]` and `[4, 5, 6]` are stacked row-wise to form a 2D array.

`np.vstack()` requires arrays to have the same number of columns.

Let's see what happens when this condition is not met.

In [ ]:
# Arrays with unequal sizes
# This is expected to fail!
array3 = np.array([7, 8])

vstack_error = np.vstack([array1, array3])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

**Explanation:**
- Vertical stacking fails because `array3` has fewer elements than `array1`.
- All arrays must have the same number of columns for `np.vstack()`.



## <span style="color: skyblue;"> Horizontal Stacking with np.hstack() </span>

`np.hstack()` stacks arrays along the horizontal axis (columns).
* All arrays must have the same number of rows for horizontal stacking.

> **[Interactive]:** Watch vstack and hstack combine arrays visually:  
> [Stacking Visualizer](https://aiml-v-izs.vercel.app/v/fd-z1y6t8h5/stacking?embed=1)\
> Select horizontal from dropdown

**Example: Horizontal Stacking**

In [ ]:
# Define arrays
array4 = np.array([[1], [2], [3]])
array5 = np.array([[4], [5], [6]])

# Stack horizontally
hstack_result = np.hstack([array4, array5])

print("Array 4:\n", array4)
print("Array 5:\n", array5)
print("Horizontal Stack:\n", hstack_result)

Array 4:
 [[1]
 [2]
 [3]]
Array 5:
 [[4]
 [5]
 [6]]
Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]

**Explanation:**
- Arrays `array4` and `array5` are stacked column-wise to form a 2D array.

`np.hstack()` requires arrays to have the same number of rows.

Let's see what happens when this condition is not met.

In [ ]:
# Arrays with unequal rows
# This is expected to fail!
array6 = np.array([[7], [8]])

hstack_error = np.hstack([array4, array6])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

**Explanation:**
- Horizontal stacking fails because `array6` has fewer rows than `array4`.
- All arrays must have the same number of rows for `np.hstack()`.

### Real world use cases

#### Vertical stacking

Zomato already has a matrix of restaurants — when new restaurants join later, instead of rebuilding the whole matrix, add new rows using `vstack`.

#### Horizontal stacking

Adding a new feature column — for instance, a popularity score — can be attached to the existing restaurant dataset using `hstack`.

<span style="color: red;"> Important:</span>
* Shapes must be compatible
* Number of columns should align for vertical stacking
* Number of rows should align for horizontal stacking

### Business Context

In Zomato analytics, we often work with multiple datasets or features that need to be combined for comprehensive analysis. Stacking arrays allows us to merge data along rows or columns efficiently:

- Vertical stacking (np.vstack): Combine multiple datasets of the same features (columns) but different restaurants (rows). Example: Adding new restaurant entries to an existing dataset.
- Horizontal stacking (np.hstack): Merge different features (columns) for the same set of restaurants (rows). Example: Combining votes, ratings, and approximate costs into a single 2D array for analysis.
- Ensures data alignment and consistency, which is crucial for downstream tasks like scoring, filtering, or visualization.
- Helps maintain structured, tabular data while performing feature engineering, aggregations, or building predictive models.


## <span style="color: skyblue;"> General Concatenation with np.concatenate() </span>

`np.concatenate()` concatenates arrays along any axis (default is `axis=0`).  
It provides more flexibility than stacking functions.

**Parameters:**
1. **array:** List or tuple of arrays to concatenate.
2. **axis:** Axis along which to concatenate.
   - `axis=0`: Concatenate rows.
   - `axis=1`: Concatenate columns (for 2D arrays).

In [ ]:
# Example 1: Concatenation Along Rows
# Concatenate along axis=0 (rows)
concat_rows = np.concatenate([array4, array5], axis=0)

print("Concatenation Along Rows:\n", concat_rows)

Concatenation Along Rows:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

**Explanation:**
- Arrays `array4` and `array5` are concatenated row-wise into a single array.

In [ ]:
# Example 2: Concatenation Along Columns
# Concatenate along axis=1 (columns)
concat_columns = np.concatenate([array4, array5], axis=1)

print("Concatenation Along Columns:\n", concat_columns)

Concatenation Along Columns:
 [[1 4]
 [2 5]
 [3 6]]

**Explanation:**
- Arrays `array4` and `array5` are concatenated column-wise into a single array.

`np.concatenate()` requires compatible dimensions along the non-concatenating axis.

Let's see what happens when this condition is not met.

In [ ]:
# Arrays with incompatible shapes
# This is expected to fail!
array7 = np.array([7, 8, 9])

concat_error = np.concatenate([array4, array7], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Explanation:**
- Concatenation along `axis=1` fails because `array7` does not match the row count of `array4`.
- Always ensure compatible dimensions for `np.concatenate()`.

<span style="color: red;"> Note:</span>
* `concatenate` needs explicit axis handling and is usually less intuitive for beginners
* In most learning cases, `vstack` and `hstack` are easier to understand and use

### Business Context

In restaurant analytics, np.concatenate() enables efficient integration of datasets across restaurants, features, or time periods. By combining rows or columns, it supports comprehensive analyses, feature engineering, and predictive modeling, ensuring aligned, complete datasets for accurate business insights.

# Question
What will be the output of:

# Choices
- [x] `[[1, 2, 3, 4]]`
- [ ] `[[1, 2], [3, 4]]`
- [ ] `[[1, 3], [2, 4]]`
- [ ] Error

# Introduction to Pandas

Pandas is not that cute animal panda.

Pandas is a powerful Python library used for working with structured data. It builds on top of **NumPy** and provides easy-to-use data structures and functions for handling structured data.

The easiest way to understand Pandas is:

* NumPy gives us arrays
* Pandas builds on top of that
* Pandas adds structure and metadata

So the conceptual flow is:

* NumPy array → Pandas Series → Pandas DataFrame

### What is missing in NumPy?

Suppose we create a NumPy array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

This gives us values. But what is missing?

* There is no column name
* There is no meaningful explicit row label
* It is not naturally table-like
* It does not directly feel like an Excel sheet

Yes, NumPy elements do have positions such as `0`, `1`, `2`, but those are implicit positions. They are not rich labels that make the data more meaningful.

### From NumPy to Series

When we convert this idea into a Pandas Series, we still have values, but now we also get metadata — a column name, explicit indexes, and better structure for reading and analysis.

A Series is:
* Still one dimensional
* Still efficient
* Still compatible with many NumPy style ideas
* But much more meaningful because it has labels

### From Series to DataFrame

If one labeled column is a Series, then multiple labeled columns together become a DataFrame. A DataFrame is table shaped — it feels like an Excel sheet, a database table, or a CSV loaded into memory. This is why Pandas becomes extremely useful in data work.

### Why Pandas is used in practice

In the real world, we do not usually receive neat vectors one by one. We usually receive data in files such as CSV, Excel, extracted reports, product logs, or tables from a database. And once data arrives, it often has problems such as missing values, mixed data types, corrupted entries, and inconsistent formatting.

So we need a library that helps us:
* Read the data
* Inspect the data
* Clean the data
* Transform the data
* Analyze the data
* Visualize the data

That is why Pandas is so important.

### Why Use Pandas?
1. **Real-World Relevance**: Pandas helps analyze large datasets efficiently, such as customer reviews, financial data, or restaurant data like our **Zomato Bangalore dataset**.
2. **Core Strengths**:
   - Data cleaning, preparation, and exploration.
   - Supports handling **missing data**.
   - Integrates seamlessly with libraries like `Matplotlib` and `NumPy`.

**Installing Pandas**

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

<span style="color: red;">Important:</span>

Just like NumPy is commonly imported as `np`, Pandas is commonly imported as `pd`. This is the standard convention — use it everywhere.

At this stage, the goal is not deep analyst level theory. The goal is strong practical familiarity that supports future AI and applied data work.

## Pandas Core Components - DataFrame and Series

Pandas has two core structures: `Series` and `DataFrame`. These two ideas must be extremely clear — everything else in Pandas builds on top of them.

### Series

A **Series** is a one-dimensional labeled array that can hold any data type. Think of it as a **single column of data** in a table.

A Pandas `Series` contains:
* Values
* An index
* Optionally a name

This makes it more powerful than a plain NumPy array.

**Mental model:** Think of it like this:
* NumPy array = values
* Series = values + labels + metadata

That extra metadata is the big idea. It allows us to work with data more naturally.

A Series can be imagined like a single Excel column: one column name, several row labels, and values aligned against those labels. That is why it feels much closer to real data than a plain vector.

**Key Features for Zomato Analysis**:
- Data is labeled using an **index** (e.g., restaurant names or IDs for easy lookup).
- Supports operations like indexing, slicing, and filtering (e.g., selecting restaurants with ratings above 4.0 or costs below Rs 500).

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/736/original/download_%281%29.png?1765259109" width="500" />

### DataFrame

A **DataFrame** is a two-dimensional table with labeled rows and columns. It is the core structure in Pandas, ideal for tabular data like the Zomato dataset.

If one labeled column is a Series, then multiple labeled columns together become a DataFrame. Each column can be thought of as a Series — so if multiple Series come together in aligned tabular form, we get a DataFrame.

**Key Features for Zomato Analysis**:
- Can hold data of different types (e.g., restaurant names as strings, ratings as floats, cost_for_two as integers).
- Labeled rows (**index**, e.g., restaurant IDs) and columns (e.g., cuisine, location).
- Provides tools for filtering (e.g., restaurants in a specific area), aggregating (e.g., average rating by cuisine), and transforming data (e.g., normalizing costs).

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/169/737/original/download_%2841%29.png?1765259184" width="500" />

Creating Series from numpy arrays (highlight that pandas is implemented using numpy):

In [ ]:
votes = np.array([120, 240, 150])
ratings = np.array([4.1, 4.5, 3.9])
restaurants = np.array(['R1', 'R2', 'R3'])

In [ ]:
votes_series = pd.Series(votes, index=['R1', 'R2', 'R3'], name='Votes')
votes_series

R1    120
R2    240
R3    150
Name: Votes, dtype: int64

Here:
* `votes` are the values
* `restaurants` are the explicit indexes
* `'Votes'` is the Series name

So the data is no longer just numbers. Now it carries context.

In [ ]:
ratings_series = pd.Series(ratings, index=['R1', 'R2', 'R3'], name='Ratings')

In [ ]:
ratings_series

R1    4.1
R2    4.5
R3    3.9
Name: Ratings, dtype: float64

Even though Series adds labels and names, it still supports many useful ideas learners already know: vectorized operations, index based access, slicing, and filtering patterns. So Series is not replacing NumPy ideas — it is building on top of them.

<span style="background-color: red;color: White;">**[Ask Learners]:**</span>

If I have only one labeled column, what is it called?

Introduce how two series can be combined into a dataframe — also a chance to introduce how concat and axis work in pandas.

### Why concatenation works here

Concatenation works properly because both Series have the same row labels. That common indexing is important — if indexes match, Pandas knows how to align rows correctly. This is one of the strongest features of labeled data.

In [ ]:
combined_df = pd.concat([votes_series,ratings_series],axis=1)

In [ ]:
combined_df

    Votes  Ratings
R1    120      4.1
R2    240      4.5
R3    150      3.9

<span style="background-color: red;color: White;">**[Ask Learners]:**</span>

If I combine multiple labeled columns together, what structure do I get?

Showcase how a dataframe can be created using a dictionary — another very common pattern in Pandas.

<span style="color: red;"> Note:</span> this part is shifted to the beginning to avoid breaking the flow from our original dataset later on.

In the dictionary approach:
* Keys become column names
* Lists become column values

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3"],
    "Votes": [120, 240, 150],
    "Rating": [4.1, 4.5, 3.9]
}
df = pd.DataFrame(data)

In [ ]:
df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9

### Summary of ways to create a DataFrame

There are at least two ways introduced:

1. Create multiple Series and concatenate them
2. Create a dictionary and pass it to `pd.DataFrame()`

Both are valid. Both are useful.

<span style="background-color: red;color: White;">Instructor Note:</span>

This is a critical concept. Spend time here. If learners confuse Series and DataFrame now, the rest of the lecture becomes harder.

## Zomato Bangalore dataset

Now we move from toy examples to a real dataset. This is the point where Pandas starts feeling practical.

Let's load our Zomato Bangalore dataset.

In [ ]:
# Downloading and unzipping the dataset
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv.

--2026-04-27 12:51:17--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.170.7.158, 3.170.7.32, 3.170.7.168, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.170.7.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M   328MB/s    in 0.2s

2026-04-27 12:51:17 (328 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: missing destination file operand after 'zomato_dataset.csv.'
Try 'mv --help' for more information.

In [ ]:
import pandas as pd

df = pd.read_csv('zomato_dataset.csv')

### Real world note on file types

In practice, data may come as CSV, Excel, or text based exports. For CSV, we use `read_csv()`. For Excel, Pandas provides `read_excel()`. Different file types usually have corresponding read functions.

### Dataset size

The lecture dataset contains 23193 rows and 17 columns — large enough to feel real, but still manageable for learning.

### What kind of columns are present?

The dataset contains restaurant related information such as address, restaurant name, online order availability, book table availability, rating, votes, location, restaurant type, famous dishes, cuisine, approximate cost for two people, and reviews. This is a good example of mixed data containing text, numbers, categorical values, and potentially messy formatting.

The dataset is relatable — learners can intuitively connect with columns like Rating, Votes, Location, Cuisine, Cost, and Online Order, which makes the lecture easier to anchor in reality.

<span style="color: red;">Important:</span>

Real world data is rarely perfect. Reading data is only the first step. Inspection and cleaning are equally important. Not all values are immediately analysis ready — for example, ratings may appear in a formatted way such as `4.5/5`. If we want to compute averages or perform numeric analysis, such fields may need cleaning first.

## Introduce head and tail as ways to get a quick glance at the data

To get a quick glance at the Zomato Bangalore dataset, we can use the `.head()` and `.tail()` methods.

### Why not print the whole DataFrame?

In the real world, data may sit on cloud infrastructure. If the dataset is huge and we print the full DataFrame unnecessarily:
* More data gets transferred
* More cost may be incurred
* Performance suffers
* It becomes a bad production habit

So instead of printing everything, preview only what is required. This is a practical engineering habit.

<span style="background-color: red;"> **[Note to Instructor]:** </span>
> Turn on location if planning to showcase the links.

In [ ]:
# What key attributes (e.g., name, rating, cost) do the first and last five restaurants in the
# Zomato Bangalore dataset reveal for performance analysis?

# Let's look at the first few rows to understand the structure
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df.tail()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

- Use `.head()` to preview the top 5 rows of the dataset.
- Use `.head(n)` to preview the top n rows of the dataset.
- Use `.tail(n)` to preview the bottom n rows of the dataset.

### Business Context for Zomato:

- Using `.head()` helps Zomato's team quickly identify key columns (e.g., restaurant_name, rating, cost_for_two) and spot sample data, such as top-rated restaurants in Bangalore.
- `.tail()` ensures the dataset is complete by checking the last entries, which might reveal data entry issues or trends in newer restaurant listings.
- These previews are critical for initial data exploration, enabling Zomato to assess data quality before analyzing customer preferences or restaurant performance.

# Basic Operations in rows

Once a DataFrame is loaded, the first thing we should do is inspect it carefully — but inspection should be efficient. Do not pull the entire dataset unless absolutely required.

We can explore or get a feel for our dataset using loc and iloc as well.


## Slicing Rows

Rows can be sliced using implicit or explicit indices. Pandas provides two key tools for slicing:

1. **`.iloc`**: Slicing based on implicit integer indices.
2. **`.loc`**: Slicing based on explicit indices.

>[Interactive]: Explore how pandas indexing works step by step before diving into the code:
[Pandas Indexing Visualizer](https://aiml-v-izs.vercel.app/v/zb-p4m2v7c8/pd-indexing?embed=1)

> Both rows and column part will be introduced later.

### What is `iloc`?

`iloc` stands for integer location based indexing. It uses row positions — meaning it works with the implicit row numbers like `0`, `1`, `2`, `3`. Even if those row numbers are not being emphasized visually, they still exist internally.

Many learners confuse position based access and label based access. Interviewers know this is a confusing topic. So build the distinction carefully from the start.

<span style="background-color: red;color: White;">Instructor Note:</span>

Say this clearly and slowly: `iloc` works with implicit position based indexing.

**Slicing Rows with `.iloc`**

Use `.iloc` for row selection by integer position:

In [ ]:
df.iloc[0]   # Access the first row

url                            https://www.zomato.com/bangalore/jalsa-banasha...
address                        942, 21st Main Road, 2nd Stage, Banashankari, ...
name                                                                       Jalsa
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                        775
phone                                             080 42297555\r\n+91 9743772233
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                                          North Indian, Mughlai, Chinese
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
Name: 0, dtype: object

In [ ]:
df.iloc[1:4]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari

In [ ]:
# How can Zomato's data team sample every third restaurant from the second to the ninth entry in the
# Bangalore dataset to explore a subset of restaurant data?
df.iloc[1:9:3]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",'700.0',"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari

In [ ]:
# How can Zomato's data team set name as the explicit index in the
# Bangalore dataset to facilitate quick lookups and analysis of specific restaurants?

df_explicit = df.set_index("name")
df_explicit

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

### Zomato Business Context:

- Setting `name` (restaurant name) as the explicit index allows Zomato's data team to quickly look up and analyze specific restaurants without scanning the entire dataset. For example, analysts can instantly retrieve details like ratings, cuisines, or average cost for a restaurant such as "Jalsa" or "Tuk-Tuk".
- An explicit index on restaurant names simplifies filtering, comparison, and grouping tasks, such as analyzing performance of the same restaurant across different areas in Bangalore or tracking changes in ratings over time.



## Use .loc to access rows based on index

`loc` always works with the explicit index values currently shown in the DataFrame. That is the easiest rule to remember.

In [ ]:
df_explicit.loc["Jalsa"]

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,804,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Paneer Lajawab, Masala Pa...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n Super ambience\nGreat...",[],Dine-out,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2/5,2173,+91 7406617555\r\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n A pretty decent place...",[],Delivery,Brookefield
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2 /5,2189,+91 7406617555\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n Friendly staff, avera...",[],Delivery,Marathahalli

You can also select multiple indices using loc.

In [ ]:
df_explicit.loc[["Jalsa", "Tuk-Tuk"]]

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,804,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Paneer Lajawab, Masala Pa...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n Super ambience\nGreat...",[],Dine-out,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2/5,2173,+91 7406617555\r\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n A pretty decent place...",[],Delivery,Brookefield
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2 /5,2189,+91 7406617555\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n Friendly staff, avera...",[],Delivery,Marathahalli
Tuk-Tuk,https://www.zomato.com/bangalore/tuk-tuk-white...,"2nd Floor, Food Court, VR Mall, Whitefield, Ba...",No,No,2.7 /5,36,+91 8105882336,Whitefield,Food Court,Biryani,North Indian,'400.0',"[('Rated 4.0', ""RATED\n I like this place bec...",[],Dine-out,Whitefield

### Very important clarification

Even after changing the index, `iloc` still works. Why? Because `iloc` does not care about visible labels. It only cares about row position.

In [ ]:
df_explicit.iloc[0]

url                            https://www.zomato.com/bangalore/jalsa-banasha...
address                        942, 21st Main Road, 2nd Stage, Banashankari, ...
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                        775
phone                                             080 42297555\r\n+91 9743772233
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                                          North Indian, Mughlai, Chinese
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
Name: Jalsa, dtype: object

In [ ]:
df_explicit.iloc[1]

url                            https://www.zomato.com/bangalore/spice-elephan...
address                        2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...
online_order                                                                 Yes
book_table                                                                    No
rate                                                                       4.1/5
votes                                                                        787
phone                                                               080 41714161
location                                                            Banashankari
rest_type                                                          Casual Dining
dish_liked                     Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
cuisines                                             Chinese, North Indian, Thai
approx_cost(for two people)                                              '800.0'
reviews_list                   [('Rated 4.0', 'RATED\n  Had been here for din...
menu_item                                                                     []
listed_in(type)                                                           Buffet
listed_in(city)                                                     Banashankari
Name: Spice Elephant, dtype: object

Changing the visible index changes how the rows are labeled. It does not erase the internal positional order. So:
* Visible index may change
* Implicit position still remains

That is why `iloc` continues to work.

<span style="background-color: red;color: White;">**[Ask Learners]:**</span>

If I convert the `name` column into the index, will `iloc[0]` stop working?

<span style="color: red;">Note:</span>

No. `iloc` is based on position, so it continues to work.

You can also reset the index to get back the original df.

In [ ]:
df_explicit.reset_index()

,name,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

### Zomato Business Context:

- Resetting the index to implicit integers (0, 1, 2, ...) simplifies row-based operations, such as slicing or iterating over restaurants.
- Using `drop=True` prevents clutter from unnecessary columns (e.g., old restaurant names as index), keeping the dataset clean for tasks like generating reports or feeding data into recommendation algorithms.
- The `inplace=True` option optimizes memory usage by updating the DataFrame directly, crucial for handling large restaurant datasets efficiently.

We can drop the index altogether.

In [ ]:
df_explicit.reset_index(drop=True)

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

## Introducing inplace

In [ ]:
df_explicit.reset_index(inplace=True)

If you use `inplace=True`, the change becomes permanent inside the same DataFrame object. If you do not save the result and do not use `inplace=True`, then the original DataFrame remains unchanged.

## Introduce .info()


<span style="color: violet;">Q. How can Zomato's data team quickly inspect the structure, column names, data types, and missing values of the Bangalore restaurant dataset to ensure its quality for analyzing restaurant performance and customer preferences?</span>

`info()` helps us quickly inspect: column names, data types, non-null counts, and memory usage. This is one of the first commands you should run on any new dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

`df.info()` gives a list of columns with:

- **Name** of columns
- **How many non-null values (blank cells)** each column has — observe location has a few nulls, which we will see how to handle later
- **Type of values** in each column — int, float, etc.

**By default**, it shows **Dtype** as `object` for anything other than **int or float**.


### Zomato Business Context:

- Knowing which columns have missing values (e.g., incomplete rating data) helps Zomato prioritize data cleaning for accurate recommendations.
- Identifying data types ensures proper handling (e.g., cost_for_two as numeric for cost analysis or rating as float for averaging).
- Memory usage insights guide Zomato in optimizing large datasets for performance in their analytics pipeline.

## Introduce .describe()


<span style="color: violet;">Q. How can Zomato's data team obtain a statistical summary of numerical columns like ratings or costs in the Bangalore restaurant dataset to identify trends in restaurant performance?</span>

`describe()` works on numeric columns. If the DataFrame has only one column currently recognized as numeric, then summary statistics appear only for that one column. After converting more columns to numeric, `describe()` will show statistics for them as well. This is why data type conversion matters.

If mean and median are far apart, that often suggests the presence of outliers — so these are not just math terms, they directly help us interpret the dataset.

In [ ]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

Observe that we are getting statistical info of only 1 column. Why? Because all other columns are in object form. We will need to typecast some of our columns to convert them into numeric forms.

### Zomato Business Context:

- `.describe()` reveals key metrics, such as the average rating or cost_for_two across Bangalore restaurants, helping Zomato identify top-performing restaurants or typical dining costs for user recommendations.
- It highlights outliers (e.g., restaurants with unusually high costs or low ratings), which can guide Zomato's restaurant success team in offering targeted support to improve performance.
- If only a few columns appear in the output (e.g., rating but not cost_for_two), it indicates non-numeric columns (stored as objects) may need typecasting to numeric for deeper analysis, such as calculating average costs or vote counts.
- These insights empower Zomato to optimize marketing campaigns, refine restaurant recommendations, or assist partners in adjusting pricing or improving service quality based on statistical trends.

# Question
If we do `df.iloc[0]`, what is returned?
# Choices
- [ ] A DataFrame containing the first row
- [x] A Series representing the first row
- [ ] A NumPy array with values from the first row
- [ ] A tuple with index and values

Explanation:

- `iloc` is purely positional indexing.
- `df.iloc[0]` fetches the first row (since Python indexing starts at $0$).
- The result is a Pandas Series, where:
    - The index of the Series corresponds to the DataFrame's columns.
    - The values are the entries in that row.

## Basic Operations on Columns

Till now, we focused on rows. Now we move to column level operations. This is where Pandas becomes very practical because most real data cleaning and transformation work happens column wise.

Columns named `approx_cost(for two people)` and `rating` are in object type when they are supposed to be in float/int form.

## Accessing Columns

You can access columns using:
- **Dot notation**: `df.column_name`  
- **Bracket notation**: `df["column_name"]`

However, square bracket notation is safer and more general, especially when column names contain spaces or special characters.

<span style="color: red;">Important:</span>

If a column name is long or contains spaces or brackets, prefer square bracket notation.

<span style="color: violet;">Q. How can Zomato's data team retrieve the approx_cost(for two people) column from the Bangalore restaurant dataset to study dining cost patterns?</span>

In [ ]:
# Accessing columns
costs = df["approx_cost(for two people)"]  # Bracket notation
print(costs)

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: approx_cost(for two people), Length: 23193, dtype: object

In [ ]:
rating = df.rate  # Dot notation
print(rating)

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

If you want more than one column, pass them in a list. This returns a smaller DataFrame containing only the selected columns.

In [ ]:
df[['approx_cost(for two people)', 'rate' ]]  #accessing multiple columns

      approx_cost(for two people)    rate
0                         '800.0'   4.1/5
1                         '800.0'   4.1/5
2                         '800.0'   3.8/5
3                         '300.0'   3.7/5
4                         '600.0'   3.8/5
...                           ...     ...
23188                    '1200.0'  3.8 /5
23189                    '2000.0'  3.9 /5
23190                    '1200.0'  2.8 /5
23191                     '800.0'  2.5 /5
23192                    '2500.0'  4.3 /5

[23193 rows x 2 columns]

### Zomato Business Context:

- Accessing the `approx_cost(for two people)` column helps Zomato analyze pricing trends across Bangalore restaurants.
- The `rate` column provides customer satisfaction scores, essential for recommending top-rated spots.

## Renaming Columns

Some datasets contain messy or hard to read column names. For example, a column like `approx_cost(for two people)` is not easy to work with repeatedly. Renaming improves readability, ease of typing, code clarity, and maintainability.

<span style="color: violet;">Q. How can Zomato's data team rename the approx_cost(for two people), votes, and rate columns to cost_for_two, Total_Votes and Ratings in the Bangalore restaurant dataset to improve clarity for analysis?</span>

<span style="background-color: red;color: White;">**[Ask Learners]:**</span>

Why would we rename a column instead of continuing with the long original name?

In [ ]:
# Renaming columns
df = df.rename(columns={"approx_cost(for two people)":'cost_for_two',"votes": "Total_Votes", "rate": "Ratings"})

# Displaying renamed DataFrame
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

### Zomato Business Context:

- Renaming `approx_cost(for two people)` to `cost_for_two` simplifies queries for pricing analysis, such as identifying affordable restaurants for Zomato users in Bangalore.
- Changing `votes` to `Total_Votes` clearly indicates customer engagement (number of reviews), aiding in ranking restaurant popularity.
- Renaming `rate` to `Ratings` ensures consistency for customer satisfaction metrics, making it easier to analyze and visualize restaurant performance.

**Key Point**: Renaming ensures clarity, especially when column names are too short or unclear or have some formatting errors.

## Adding a New Column

Add a new column by assigning data to a new column name.

### Problem with the ratings column

The ratings are not stored as plain numbers. They appear in forms such as `4.1/5` or `3.9/5`. This is a problem — if we want to calculate average rating, maximum rating, or filter on rating, the values must be numeric. Right now they are strings.

We want to remove the `/5` part and keep only the numeric value. We do this using string slicing — starting from index `0` and stopping before the last two characters. So `4.1/5` becomes `4.1`.

In [ ]:
# Adding a new column
df["only_rating"] = df["Ratings"].str[:-2]

# Displaying a new column
df["only_rating"]

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: object

This creates a new column called `only_rating`. When you create a new column like this, Pandas adds it as a new column in the DataFrame. By default, newly created columns are added at the end — so if the DataFrame originally had 17 columns, this becomes the 18th column.

As you can see, the rating is still in object type. We need to convert it into a float type.

In [ ]:
# It is expected to fail!
df["only_rating"] = df["only_rating"].astype(float)

ValueError: could not convert string to float: 'N'

<span style="color: violet;">It is failing because it looks like there is an 'N' in the ratings column, which cannot be converted into a float. What are our options?</span>

This is a common real world data cleaning scenario — always assume that some amount of real world data is corrupted or inconsistent. Some rows may contain values like `NEW/5`. After slicing, this may still result in invalid strings such as `NEW`. If we try to convert that directly to float, it fails.

### Option 1

**Replacing certain values in object type columns**

In [ ]:
df["only_rating"] = df["only_rating"].replace('N', np.nan)

In [ ]:
df["only_rating"] = df["only_rating"].astype(float)

It is now working

### Option 2

**Use pd.to_numeric with errors='coerce'**

`pd.to_numeric` converts a column into a numeric type. `errors='coerce'` is a parameter that will force the operation and convert values it cannot handle into nulls. It tells Pandas: if conversion is valid, convert it; if conversion fails, turn it into a missing value. Instead of crashing, Pandas handles them gracefully.

In [ ]:
df["only_rating"] = pd.to_numeric(df["only_rating"], errors='coerce')

In [ ]:
df["only_rating"]

0        4.1
1        4.1
2        3.8
3        3.7
4        3.8
        ...
23188    3.8
23189    3.9
23190    2.8
23191    2.5
23192    4.3
Name: only_rating, Length: 23193, dtype: float64

In [ ]:
df["cost_for_two"]

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: cost_for_two, Length: 23193, dtype: object

In [ ]:
df["cost_for_two"] = pd.to_numeric(df["cost_for_two"].str.strip("'\""), errors="coerce")

In [ ]:
df["cost_for_two"]

0         800.0
1         800.0
2         800.0
3         300.0
4         600.0
          ...
23188    1200.0
23189    2000.0
23190    1200.0
23191     800.0
23192    2500.0
Name: cost_for_two, Length: 23193, dtype: float64

If `cost_for_two` remains text, then operations like sorting by cost, average cost, dividing by 2, or filtering expensive restaurants will not work properly.

In [ ]:
# Adding a new column
df['cost_for_one']  = df['cost_for_two'] / 2

# Displaying a new column
df['cost_for_one']

0         400.0
1         400.0
2         400.0
3         150.0
4         300.0
          ...
23188     600.0
23189    1000.0
23190     600.0
23191     400.0
23192    1250.0
Name: cost_for_one, Length: 23193, dtype: float64

### Creating boolean columns

We can also create boolean columns using conditions. This is very useful in real products — you may have seen platforms show labels such as "high rated restaurant", "trending place", "low cancellation driver", or "frequently ordered item". These kinds of indicators are often built using boolean logic like this.

In [ ]:
df["is_good"] = df["only_rating"] > 4
df["is_good"]

0         True
1         True
2        False
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192     True
Name: is_good, Length: 23193, dtype: bool

<span style="background-color: red;color: White;">Instructor Note:</span>

Make sure learners understand that most column operations follow a pattern:
* inspect the column
* identify formatting issue
* clean the string
* convert type
* derive useful features

# Question
Which of the following is the correct way to rename a column "A" to "B" in a DataFrame `df`?
# Choices
- [x] `df.rename(columns={"A": "B"})`
- [ ] `df.changeTo("A", "B")`
- [ ] `df.columns("A"="B")`
- [ ] `df.change(columns={"A": "B"})`

Explanation:

`df.rename(columns={"A": "B"})` is the correct syntax. By default, it returns a new DataFrame unless `inplace=True` is used.