<a href="https://colab.research.google.com/github/Hellohiavinash/Machine_Learning_Projects/blob/main/Copy_of_Food_Delivery_Data_Exploration_and_analysis_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Food Delivery Data Exploration and analysis 5

## <span style="color: skyblue;"> Agenda </span>

* Unique values, value counts, and duplicates
* Working with Both Rows and Columns
* Handling Duplicate Records in a DataFrame
* Pandas Built-In Operations - Aggregate Functions
* Sorting Values in Pandas
> <span style="color: red;"> **Note:** </span> <span style="background-color: Blue;">[Link](https://colab.research.google.com/drive/1EG-NsxWCPdfTo1T9yFqKV3wfKVWNHhor?usp=sharing)</span> of the colab notebook used in the lecture and to be shared with learners.

# Unique Value and Value Count

## Unique Values in a Column

When working with a real dataset, one common requirement is to understand the different values present in a column.

For example, in the Zomato dataset, the `location` column may contain values like Banashankari, JP Nagar, Whitefield, Jayanagar, BTM, and Koramangala. The same location can appear many times because multiple restaurants may exist in the same area.

### Why unique values are needed

Suppose we want to know: *What are all the unique areas where Zomato is serving?*

Printing the entire `location` column will not help much because many values will repeat. We need only one occurrence of each location.

Why is `describe()` not enough here? `describe()` gives statistical information — count, mean, standard deviation, minimum, maximum, and quartiles. For numeric columns this is useful, but if we want to know the unique values in a categorical column, `describe()` is not the best method.

The `df["column_name"].unique()` method lists unique values in a column.

> [Interactive]: See how unique values and value counts are computed step by step before diving into the code: [Unique & Value Counts Visualizer](https://aiml-v-izs.vercel.app/v/zb-p4m2v7c8/pd-columns?embed=1)
Select Unique from dropdown.


<span style=" color: red;">Narrative:</span> you want to see which locations and the number of unique locations these restaurants belong to.

In [ ]:
# we will import the data from last class.
!gdown 1YBEwvF07zaNNqW8sMPrwmgl4s73EPU_S

Downloading...
From (original): https://drive.google.com/uc?id=1YBEwvF07zaNNqW8sMPrwmgl4s73EPU_S
From (redirected): https://drive.google.com/uc?id=1YBEwvF07zaNNqW8sMPrwmgl4s73EPU_S&confirm=t&uuid=d448de4f-7757-4555-8f20-c57ee1a7f878
To: /content/data.csv
100% 486M/486M [00:07<00:00, 67.5MB/s]

In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')

In [ ]:
# Finding unique values in the 'location' column
unique_locations = df["location"].unique()
print(unique_locations)

['Banashankari' 'Basavanagudi' 'Jayanagar' 'Kumaraswamy Layout'
 'Rajarajeshwari Nagar' 'Mysore Road' 'Uttarahalli' 'South Bangalore'
 'Vijay Nagar' 'Bannerghatta Road' 'JP Nagar' 'BTM' 'Wilson Garden'
 'Koramangala 5th Block' 'Shanti Nagar' 'Richmond Road' 'City Market'
 'Bellandur' 'Sarjapur Road' 'Marathahalli' 'HSR' 'Old Airport Road'
 'Indiranagar' 'Koramangala 1st Block' 'East Bangalore' 'MG Road'
 'Brigade Road' 'Lavelle Road' 'Church Street' 'Ulsoor' 'Residency Road'
 'Shivajinagar' 'Infantry Road' 'St. Marks Road' 'Cunningham Road'
 'Race Course Road' 'Domlur' 'Koramangala 8th Block' 'Frazer Town'
 'Ejipura' 'Vasanth Nagar' 'Jeevan Bhima Nagar' 'Old Madras Road'
 'Commercial Street' 'Koramangala 6th Block' 'Majestic' 'Langford Town'
 'Koramangala 7th Block' 'Brookefield' 'Whitefield'
 'ITPL Main Road, Whitefield' 'Varthur Main Road, Whitefield'
 'Koramangala 2nd Block' 'Koramangala 3rd Block' 'Koramangala 4th Block'
 'Koramangala' 'Bommanahalli' 'Hosur Road' 'Seshadripuram'
 'Electronic City' 'Banaswadi' 'North Bangalore' 'RT Nagar' 'Kammanahalli'
 'Hennur' 'HBR Layout' 'Kalyan Nagar' 'Thippasandra' 'CV Raman Nagar'
 'Kaggadasapura' 'Kanakapura Road' 'Nagawara' 'Rammurthy Nagar'
 'Sankey Road' 'Central Bangalore' 'Malleshwaram' 'Sadashiv Nagar'
 'Basaveshwara Nagar' 'Rajajinagar' 'New BEL Road' 'West Bangalore'
 'Yeshwantpur' 'Sanjay Nagar' 'Sahakara Nagar' 'Jalahalli' 'Yelahanka'
 'Magadi Road' 'KR Puram']

### Using `nunique()`

Sometimes, we do not want to print all unique values — we only want to know how many unique values exist.

Here is the key difference between related functions:
* `unique()` gives the actual unique values
* `nunique()` gives the number of unique values
* `count()` counts every row where the value is present — if `Banashankari` appears 100 times, it is counted 100 times
* `nunique()` counts only distinct values — if `Banashankari` appears 100 times, it is counted only once

The `df["column_name"].nunique()` method lists the number of unique values in a column.

In [ ]:
number_of_unique_locations = df["location"].nunique()
print(number_of_unique_locations)

88

This means there are 88 unique locations in the `location` column.

## Value Counts in a Column

The `df["column_name"].value_counts()` method counts occurrences of each unique value.

### Business use case for `value_counts()`

A business may not only want to know the unique locations — it may also want to know how many restaurants exist in each location. This can help with decisions like:
* Where more delivery riders are needed
* Which area has more restaurant density
* Which locations may generate more orders
* Where operations should be strengthened

`value_counts()` is one of the most useful Pandas functions. It is commonly used in data exploration, machine learning, categorical column analysis, business reporting, and understanding distributions.

> [Interactive]: See how unique values and value counts are computed step by step before diving into the code: [Unique & Value Counts Visualizer](https://aiml-v-izs.vercel.app/v/zb-p4m2v7c8/pd-columns?embed=1)
Select Value Counts from dropdown.

<span style="color: red;">Narrative:</span> you might want to find out which are the most popular locations that people order from / dine in

In [ ]:
# How can Zomato's data team count the number of restaurants in each unique location in the
# Bangalore dataset to identify the most popular dining or ordering areas?

# Counting occurrences of each unique value
location_counts = df["location"].value_counts()
location_counts

location
Koramangala 5th Block    1783
BTM                      1456
Indiranagar              1350
HSR                      1162
Jayanagar                1037
                         ...
Kanakapura Road             2
West Bangalore              2
Yelahanka                   2
Magadi Road                 2
KR Puram                    1
Name: count, Length: 88, dtype: int64

This result is already sorted by frequency — `Koramangala 5th Block` has the highest number of restaurants, followed by BTM.

<span style="color: violet;">Question: Which is the most ordered restaurant in the dataset?</span>

We can also use `value_counts()` on the restaurant name column to identify restaurant chains with many branches.

In [ ]:
restaurant_order_counts = df["name"].value_counts()
restaurant_order_counts

name
Onesta               85
Empire Restaurant    69
KFC                  59
McDonald's           57
Pizza Hut            56
                     ..
Bao & Grills          1
Gongura               1
Tuk-Tuk               1
Karibu - The Zuri     1
Fujian Express        1
Name: count, Length: 3159, dtype: int64

### Business use case for restaurant chains

If a restaurant chain has many branches in the same city, it becomes important for a platform like Zomato. For example, KFC may have branches in multiple areas, McDonald's may have branches across the city, and Onesta may have many outlets.

A food delivery platform can use this information to:
* Identify strong restaurant chains
* Negotiate platform commission
* Plan business partnerships
* Understand chain-level coverage

If Zomato usually charges 5 percent commission, a large chain may negotiate and ask for a lower commission because it brings more business.

<span style="color: violet;">Which type of listing (e.g., delivery, dine-out, etc.) is the most common?</span>

In [ ]:
listing_counts = df['listed_in(type)'].value_counts()
listing_counts

listed_in(type)
Delivery              10625
Dine-out               8009
Desserts               1333
Cafes                  1047
Drinks & nightlife      890
Buffet                  762
Pubs and bars           527
Name: count, dtype: int64

<span style="background-color: red;color: White;">**[Ask Learners]:**</span>

Use `value_counts()` on the restaurant type column and find how many records exist for each type.

### Zomato Business Context:

- **Location Counts**: High counts for locations like Koramangala or Indiranagar indicate demand hotspots, allowing Zomato to allocate more delivery riders or target promotions in these areas.
- **Restaurant Orders**: Identifying the most ordered restaurants (e.g., a chain appearing frequently) helps Zomato prioritize partnerships, feature them in promotions, or include them in loyalty programs like Zomato Gold.
- **Listing Types**: A dominance of delivery listings suggests a preference for online orders, guiding Zomato to enhance delivery logistics or focus app features on delivery options over dine-out in Bangalore.

# Working with Both Rows and Columns

When analyzing data, you often need to work with both rows and columns simultaneously. Pandas provides powerful tools for selecting, slicing, and filtering data across multiple axes.

**Key Tools for Selection**:
1. **`.iloc`**: Select rows and columns by integer position.
2. **`.loc`**: Select rows and columns by labels.

> [Interactive]: Explore how pandas indexing works step by step before diving into the code:
[Pandas Indexing Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-indexing?embed=1)

> Select rows + cols from dropdown


## <span style="color: skyblue;"> Using `.iloc` for Rows and Columns </span>

The `.iloc` method allows you to:
1. Select specific rows and columns by their integer indices.
2. Slice rows and columns together.

#### Example: Selecting Specific Rows and Columns

In [ ]:
# Select the first two rows and the first two columns
df.iloc[0:2, 0:2]

,url,address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."

In [ ]:
# Select the last two rows and the last column
df.iloc[-2:, -1]

23191    False
23192     True
Name: is_good, dtype: bool

## <span style="color: skyblue;"> Using .iloc to Modify Data ( Would want to use the same dataset instead of creating a new one) </span>

In [ ]:
# For restaurants R2 and R3 on Zomato, update their number of votes and
# ratings to reflect recent changes in customer engagement and feedback.
# How can we modify the DataFrame to apply these updates at once?


# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

sample_df = pd.DataFrame(data)

# Assigning new values to multiple rows and columns
sample_df.iloc[1:3, 1:3] = [[300, 4.7], [180, 4.2]]

print("DataFrame after modifying rows and columns:")
print(sample_df)

DataFrame after modifying rows and columns:
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

## <span style="color: skyblue;"> Using .loc to Select Rows and Columns </span>

The `.loc` method allows you to:
- Filter rows based on conditions.
- Update specific rows and columns by labels.


<span style=" color: red;">Narrative:</span> Your manager/team wants you to flag a few restaurants as 1, 0, or -1 based on customer/delivery partner feedback feedback

In [ ]:
# Zomato wants to mark all restaurants with an initial flag to track them for future analysis or promotions.
# How can we add a new column flag and set it to 1 for all restaurants in the DataFrame?

#create a new column to keep track of flags - initially set it as 1 for all restaurants
df['flag'] = 1

In [ ]:
df

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,...,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,...,"North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,...,"Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining",...,"Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,...,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,...,"North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining",...,"North Indian, Continental, Mediterranean",1200.0,"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,3.8,600.0,False,1
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",...,Finger Food,2000.0,"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,3.9,1000.0,False,1
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar",...,"Chinese, Continental, North Indian",1200.0,"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,2.8,600.0,False,1
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar",...,"Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.5,400.0,False,1
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,...,Finger Food,2500.0,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.3,1250.0,True,1

In [ ]:
# Setting 'Restaurant' as the index
df_explicit = df.set_index("name")

# Select specific rows ('R2' and 'R3') and specific columns ('flag')
print(df_explicit.loc[["Jalsa", "Grand Village"], ["flag"]])
print("==="*10)

# Updating the 'flag' for restaurant 'Jalsa.'
df_explicit.loc["Jalsa", "flag"] = 0
print("Updated DataFrame:")
df_explicit

               flag
name
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Grand Village     1
Grand Village     1
Grand Village     1
Grand Village     1
==============================
Updated DataFrame:

,url,address,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
name,,,,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,0
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200.0,"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,3.8,600.0,False,1
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000.0,"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,3.9,1000.0,False,1
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200.0,"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,2.8,600.0,False,1
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.5,400.0,False,1
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500.0,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.3,1250.0,True,1

## <span style="color: skyblue;"> Using .loc for Conditional Updates </span>

<span style=" color: red;">Narrative:</span> You also receive information to flag restaurants with ratings less than 3 as -1 and between 3 and 4 as 0

In [ ]:
# Zomato wants to identify underperforming restaurants with ratings below 3 and mark them for review.
# How can we update the flag column to -1 for all restaurants where only_rating is less than 3?

# Update 'Rating' for all restaurants with 'Votes' greater than 200
df_explicit.loc[df_explicit["only_rating"] < 3, "flag"] = -1

## <span style="color: skyblue;"> Combining DataFrames with `concat.` </span>

The `concat` function allows you to combine multiple DataFrames:
1. **Row-wise Concatenation**: Add rows from another DataFrame.
2. **Column-wise Concatenation**: Add new columns from another DataFrame.

**1. Row-wise Concatenation**

You can stack two DataFrames vertically to combine their rows:

In [ ]:
# How can Zomato's data team combine a new set of restaurant data (e.g.,
# new Bangalore restaurants) Can the existing dataset be used to create a unified DataFrame for comprehensive analysis?


# Creating a second DataFrame
data2 = {
    "Restaurant": ["R5", "R6"],
    "Votes": [90, 110],
    "Rating": [3.8, 4.3]
}

df2 = pd.DataFrame(data2)

# Concatenating row-wise
combined_df = pd.concat([sample_df, df2], ignore_index=True)
print("Combined DataFrame (Row-wise):")
print(combined_df)

Combined DataFrame (Row-wise):
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R5     90     3.8
5         R6    110     4.3

### <span style=color:orange> Zomato Business Context:</span>

- Row-wise concatenation allows Zomato to append new restaurant data (e.g., newly onboarded restaurants in Bangalore) to the existing dataset, ensuring the dataset stays up-to-date for user recommendations.
- Using ignore_index=True creates a new numerical index, simplifying analysis by maintaining a clean, sequential order for all restaurants.
- This approach helps Zomato integrate data from multiple sources (e.g., new restaurant listings or partner updates), supporting comprehensive market analysis and personalized dining suggestions.

**2. Column-wise Concatenation**

You can stack DataFrames side-by-side to add new columns:

In [ ]:
# Creating a DataFrame with new columns
new_columns = {
    "Delivery Time (mins)": [30, 25, 35, 20, 40, 28]
}

df_new_cols = pd.DataFrame(new_columns)

# Concatenating column-wise
final_df = pd.concat([combined_df, df_new_cols], axis=1)
print("Final DataFrame (Column-wise):")
final_df

Final DataFrame (Column-wise):

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.1                    30
1         R2    300     4.7                    25
2         R3    180     4.2                    35
3         R4     80     4.0                    20
4         R5     90     3.8                    40
5         R6    110     4.3                    28

### <span style=color:orange> Zomato Business Context:</span>

- Adding a Delivery Time (mins) column enhances the dataset by providing insights into delivery efficiency, a key factor for Zomato users choosing restaurants in Bangalore.
- Column-wise concatenation with axis=1 allows Zomato to integrate new data (e.g., delivery performance metrics) from external sources, such as logistics partners, into the existing restaurant dataset.
- This enriched dataset supports Zomato in optimizing delivery operations, prioritizing restaurants with faster delivery times for user recommendations, or identifying restaurants needing logistics improvements to enhance customer satisfaction.

> **Real-World Analogy:** Adding a new column is common in real datasets. For example, in an education platform, a new test may be introduced for a batch and the marks of that test need to be added to the existing student table — the test score becomes a new column. This is exactly why column-wise concatenation is an important operation.

### Practice Questions

1. **Using `.iloc`**, retrieve the first two rows and the last column.

In [ ]:
# 1. Using `.iloc` to retrieve the first two rows and the last column
sample_df.iloc[:2, -1]

0    4.1
1    4.7
Name: Rating, dtype: float64

2. **Using `.loc`**, update the 'Rating' for restaurants with votes below 150 to 4.0.

In [ ]:
# 2. Using `.loc` to update 'Rating' for restaurants with votes < 150
sample_df.loc[sample_df["Votes"] < 150, "Rating"] = 4.0
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.0
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

3. Add a new row to the DataFrame for a restaurant 'R7' with 100 votes and a rating of 3.7.

In [ ]:
# 3. Adding a new row,

new_row = pd.DataFrame([["R7", 100, 3.7]], columns=sample_df.columns)
sample_df = pd.concat([sample_df, new_row], ignore_index=True)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.0
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R7    100     3.7

4. Concatenate two DataFrames:
   - One with restaurant data.
   - One with a column showing average delivery time.

In [ ]:
# 4. Concatenating two DataFrames
df_with_time = pd.DataFrame({"Delivery Time (mins)": [30, 40, 20, 35, 25]})
final_combined_df = pd.concat([sample_df, df_with_time], axis=1)
final_combined_df

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.0                    30
1         R2    300     4.7                    40
2         R3    180     4.2                    20
3         R4     80     4.0                    35
4         R7    100     3.7                    25

5. Find the updated 'Rating' for restaurants with votes greater than 200 after combining two DataFrames.

In [ ]:
# 5. Finding updated 'Rating' for restaurants with votes > 200
updated_ratings = final_combined_df.loc[final_combined_df["Votes"] > 200, "Rating"]
print(updated_ratings)

1    4.7
Name: Rating, dtype: float64

# Handling Duplicate Records in a DataFrame

I would showcase using the current dataset itself, instead of creating a new df. Creating story lines for removing duplicates is easy anyway.

In real-world datasets, duplicate records are common and can affect analysis. Pandas provides simple methods to identify and remove duplicates efficiently.

## <span style="color: skyblue;"> Key Methods for Handling Duplicates </span>

### 1. Identifying Duplicate Rows with `df.duplicated().`

The `df.duplicated()` method:
- Returns `True` for duplicate rows (excluding the first occurrence by default).
- You can customize its behavior using the `keep` parameter:
  - `keep='first'` (default): Marks all duplicates except the first occurrence.
  - `keep='last'`: Marks all duplicates except the last occurrence.
  - `keep=False`: Marks **all** duplicates as `True`.

> [Interactive]: Learn how duplicates are identified and handled step by step before exploring the code:
[Duplicates Handling Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-duplicates?embed=1)

In [ ]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
# Identifying duplicate rows
print("Duplicate rows (keep='first'):")
print(sample_df.duplicated())  # Default behavior

Duplicate rows (keep='first'):
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
print("Duplicate rows (keep='last'):")
print(sample_df.duplicated(keep="last"))

Duplicate rows (keep='last'):
0     True
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
print("Duplicate rows (keep=False):")
print(sample_df.duplicated(keep=False))

Duplicate rows (keep=False):
0     True
1     True
2    False
3     True
4    False
5     True
dtype: bool

**Key Points**
- **Default (`keep='first'`)**: Treats the first occurrence of a duplicate as unique.
- **`keep='last'`**: Treats the last occurrence of a duplicate as unique.
- **`keep=False`**: Marks all duplicates as `True`.

### <span style=color:orange> Zomato Business Context:</span>

- Identifying duplicates ensures Zomato’s dataset accurately represents unique restaurants, preventing inflated metrics like total votes or skewed average ratings.
- For example, duplicate entries for a restaurant like “Cafe Coffee Day” could overstate its popularity, affecting recommendation algorithms or marketing decisions.
Checking duplicates helps Zomato maintain data integrity, ensuring reliable insights for user recommendations, restaurant rankings, or market coverage analysis in Bangalore.


### 2. Removing Duplicate Rows

The `df.drop_duplicates()` method removes duplicate rows based on the specified conditions:
- By default, it keeps the first occurrence of each duplicate row.
- You can use the `keep` parameter to change this behavior.

In [ ]:
# Removing duplicates (keep='first')
df_no_duplicates_first = sample_df.drop_duplicates(keep="first")
print("DataFrame after removing duplicates (keep='first'):")
print(df_no_duplicates_first)

DataFrame after removing duplicates (keep='first'):
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
# Removing duplicates (keep='last')
df_no_duplicates_last = sample_df.drop_duplicates(keep="last")
print("DataFrame after removing duplicates (keep='last'):")
print(df_no_duplicates_last)

DataFrame after removing duplicates (keep='last'):
  Restaurant  Votes  Rating
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
# Removing all duplicates (keep=False)
df_no_duplicates_all = sample_df.drop_duplicates(keep=False)
print("DataFrame after removing all duplicates (keep=False):")
print(df_no_duplicates_all)

DataFrame after removing all duplicates (keep=False):
  Restaurant  Votes  Rating
2         R3    150     3.9
4         R4     80     4.0

### 3. Removing Duplicates Based on Specific Columns

Sometimes, you might want to check duplicates only for certain columns. Use the `subset` parameter in `df.drop_duplicates()` to specify the columns to consider for duplication.

- Use `subset` in `df.drop_duplicates()` to check duplicates for specific columns.

In [ ]:
# Removing duplicates based on the 'Votes' column
df_no_duplicates_subset = sample_df.drop_duplicates(subset=["Votes"], keep="first")
print("DataFrame after removing duplicates based on 'Votes':")
print(df_no_duplicates_subset)

DataFrame after removing duplicates based on 'Votes':
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
# Removing duplicates based on 'Restaurant' and 'Votes.'
df_no_duplicates_multi_subset = sample_df.drop_duplicates(subset=["Restaurant", "Votes"], keep="first")
print("DataFrame after removing duplicates based on 'Restaurant' and 'Votes':")
print(df_no_duplicates_multi_subset)

DataFrame after removing duplicates based on 'Restaurant' and 'Votes':
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

### <span style=color:orange> Zomato Business Context:</span>

- Removing duplicates based on Total_Votes ensures Zomato avoids overcounting restaurants with identical review counts, refining popularity metrics for user recommendations.
- Using subset=["name", "Total_Votes"] checks for restaurants with the same name and vote count, which could indicate erroneous duplicate entries (e.g., a chain listed twice in the same location), improving data quality for restaurant rankings.
- These operations help Zomato maintain a clean dataset, ensuring accurate insights for marketing campaigns, delivery logistics, or identifying top-performing restaurants in Bangalore.

### Real-World Use Case: Plagiarism Detection

Consider a student assignment dataset. There may be a column called `assignment_submission`. If two students submit exactly the same assignment content, we may want to identify that duplication.

In this case:
* The whole row need not be same
* Student names may be different
* Student IDs may be different
* Only the assignment submission may be same

So duplicate checking can be done only on the assignment column:

```
# This is just for demo. Do not run this
student_df.drop_duplicates(subset=["assignment_submission"], keep=False)
```

Using `keep=False` marks or removes **all** duplicate submissions — useful when both copied submissions should be treated as duplicates. This is a real-world example of where column-level duplicate checking is more meaningful than full-row duplicate checking.

# Question
Which statement about `df.drop_duplicates()` is FALSE?
# Choices
- [ ] By default, it keeps the first occurrence of each duplicate row
- [ ] The subset parameter lets you specify columns to check duplicates
- [x] It removes duplicate columns instead of rows
- [ ] The `keep=False` option removes all duplicates


Explanation:
`df.drop_duplicates()` operates on rows, not columns.

# Pandas Built-In Operations - Aggregate Functions

[Interactive]: Understand how aggregate functions compute summaries across data step by step before diving into the code:
[Aggregate Functions Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-aggregation?embed=1)

> Show different operations from dropdown.

In [ ]:
# Sum of votes
print("Total Votes:", df["Total_Votes"].sum())

Total Votes: 13940720

In [ ]:
# Count of ratings
print("Number of Ratings:", df["only_rating"].count())

Number of Ratings: 23046

In [ ]:
# Average cost for two
print("Average Cost for Two:", df["cost_for_two"].mean())

Average Cost for Two: 755.90436769715

## <span style="color: skyblue;"> Applying Aggregate Functions on Multiple Columns </span>
You can also apply aggregate functions across multiple columns using the .agg() method.

**Example: Aggregating Across Columns**

In [ ]:
# Aggregating multiple columns
aggregates = df[["Total_Votes", "cost_for_two"]].agg(["sum", "mean", "min", "max"])
print("Aggregates for Votes and Cost for Two:")
aggregates

Aggregates for Votes and Cost for Two:

       Total_Votes  cost_for_two
sum   1.394072e+07  1.753169e+07
mean  6.010745e+02  7.559044e+02
min   0.000000e+00  4.000000e+01
max   1.683200e+04  6.000000e+03

### <span style=color:orange> Zomato Business Context:</span>

- Using .agg() on Total_Votes and cost_for_two reveals key metrics, such as total engagement (sum), average costs (mean), and cost range (min, max), helping Zomato identify market trends.
- For example, a high max cost could highlight premium restaurants for Zomato Gold promotions, while a low min cost could inform budget-friendly dining campaigns.
- These aggregates support strategic decisions, like optimizing restaurant recommendations, targeting marketing in high-engagement areas, or advising restaurant partners on pricing strategies in Bangalore.

# Sorting Values in Pandas

> [Interactive]: See how sorting rearranges data step by step before diving into the code:
[Sorting Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-sorting?embed=1)


## <span style="color: skyblue;"> Sorting by a Single Column </span>

In [ ]:
# Sorting rows by the "Votes" column in ascending order
sorted_votes_asc = sample_df.sort_values(by="Votes", ascending=True)
print("DataFrame sorted by Votes (ascending):")
print(sorted_votes_asc)

DataFrame sorted by Votes (ascending):
  Restaurant  Votes  Rating
4         R4     80     4.0
0         R1    120     4.1
5         R1    120     4.1
2         R3    150     3.9
3         R2    240     4.5
1         R2    240     4.5

In [ ]:
# Sorting rows by the "Votes" column in descending order
sorted_votes_desc = sample_df.sort_values(by="Votes", ascending=False)
print("DataFrame sorted by Votes (descending):")
print(sorted_votes_desc)

DataFrame sorted by Votes (descending):
  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0

## <span style="color: skyblue;"> Sorting by Multiple Columns </span>

**Example: Sorting by "Votes" and "Rating"**

You can sort rows based on multiple columns by passing a list of column names.

### Step-by-Step Logic for Multi-Column Sorting

Consider a dataset with `age` and `salary`:

| age | salary |
| --- | --- |
| 20 | 20000 |
| 20 | 30000 |
| 21 | 40000 |
| 19 | 20000 |
| 21 | 20000 |

Suppose we want `age` in ascending order and `salary` in descending order. The **first priority** is given to `age`. Only when there is a tie in `age` is salary used to break the tie.

**Step 1:** Sort by `age` ascending → `19, 20, 20, 21, 21`

**Step 2:** For age `20`, salaries are `20000, 30000`. Since salary should be descending → `30000, 20000`

**Step 3:** For age `21`, salaries are `40000, 20000`. Already descending — no change.

**Final sorted result:**

| age | salary |
| --- | --- |
| 19 | 20000 |
| 20 | 30000 |
| 20 | 20000 |
| 21 | 40000 |
| 21 | 20000 |

> **Key Rule:** The first column has the highest priority. The next column is used only when values in the previous column are tied.

> <span style="color: red;">**Common Mistake:**</span> Learners sometimes think that every column is sorted independently. That is **not correct**. Pandas rearranges complete rows — it does not break the relationship between columns.

In [ ]:
# Sorting by Votes (descending) and then by Rating (ascending)
sorted_multi = sample_df.sort_values(by=["Votes", "Rating"], ascending=[False, True])
print("DataFrame sorted by Votes (descending) and Rating (ascending):")
sorted_multi

DataFrame sorted by Votes (descending) and Rating (ascending):

  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0

### <span style=color:orange> Zomato Business Context:</span>

- Sorting by Total_Votes (descending) and only_rating (ascending) ranks highly engaged restaurants while resolving ties by rating, helping Zomato identify top-performing restaurants for recommendations or Zomato Gold promotions.
- This approach supports nuanced analysis, such as finding restaurants with high votes but lower ratings, which may need support from Zomato’s restaurant success team to improve customer satisfaction in Bangalore.


**Some Practice Questions**

<span style="background-color: red;"> **[Ask Learners]:** </span>
Give them some time (around 2 min) to solve the following one by one and then show the answer.

1. Sort the DataFrame by "Rating" in descending order.
2. Find the restaurant with the highest rating after sorting.
3. Sort the DataFrame first by "Cost for Two" (ascending) and then by "Votes" (descending).
4. Create a new sorted DataFrame based on "Votes" and "Rating" and display the top 3 rows.

# Question
What is the effect of the following code?
`df.sort_values(by=["age", "salary"], ascending=[True, False])`
# Choices
- [x] Sorts by age (ascending), then by salary (descending)
- [ ] Sorts by salary first, then age
- [ ] Sorts both columns in ascending order
- [ ] Throws an error due to multiple columns

Explanation:

When multiple columns are passed to `by`, the ascending list specifies sort order for each column in the same order.