<a href="https://colab.research.google.com/github/Hellohiavinash/Machine_Learning_Projects/blob/main/Pandas_FDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Downloading and unzipping the dataset
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv.

--2026-09-23 15:47:00--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 13.225.41.45, 13.225.41.18, 13.225.41.124, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|13.225.41.45|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M   136MB/s    in 0.5s

2026-09-23 15:47:01 (136 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: missing destination file operand after 'zomato_dataset.csv.'
Try 'mv --help' for more information.

In [ ]:
import pandas as pd

df=pd.read_csv('/content/zomato_dataset.csv')
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
#charateristics of the dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

In [ ]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

In [ ]:
df.shape

(23193, 17)

In [ ]:
df['rate']

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

In [ ]:
df['rate'].shape

(23193,)

In [ ]:
x= ['rate', 'votes']
df[x]

         rate  votes
0       4.1/5    775
1       4.1/5    787
2       3.8/5    918
3       3.7/5     88
4       3.8/5    166
...       ...    ...
23188  3.8 /5    128
23189  3.9 /5     77
23190  2.8 /5    161
23191  2.5 /5     81
23192  4.3 /5    236

[23193 rows x 2 columns]

In [ ]:
df[['rate','votes']]

         rate  votes
0       4.1/5    775
1       4.1/5    787
2       3.8/5    918
3       3.7/5     88
4       3.8/5    166
...       ...    ...
23188  3.8 /5    128
23189  3.9 /5     77
23190  2.8 /5    161
23191  2.5 /5     81
23192  4.3 /5    236

[23193 rows x 2 columns]

In [ ]:
#fetch the 50th row
#fetch it using index location

df.iloc[49]

url                            https://www.zomato.com/bangalore/rolls-on-whee...
address                        Shop 33 & 30, 21st Main, Near BDA Complex, 2nd...
name                                                             Rolls On Wheels
online_order                                                                  No
book_table                                                                    No
rate                                                                       3.6/5
votes                                                                        299
phone                                           +91 9071734101\r\n+91 9071496800
location                                                            Banashankari
rest_type                                                            Quick Bites
dish_liked                     Rolls, Momos, Fries, Veggie Roll, Chicken Keba...
cuisines                                                 Fast Food, Rolls, Momos
approx_cost(for two people)                                              '300.0'
reviews_list                   [('Rated 3.0', "RATED\n  Had the urge to have ...
menu_item                                                                     []
listed_in(type)                                                         Delivery
listed_in(city)                                                     Banashankari
Name: 49, dtype: object

In [ ]:
df.iloc[2:10]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,'600.0',"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
6,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",'600.0',"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
7,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",'700.0',"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
8,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",'550.0',"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari
9,https://www.zomato.com/bangalore/caf%C3%A9-dow...,"12,29 Near PES University Back Gate, D'Souza N...",CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1/5,402,080 26724489\r\n+91 7406048982,Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,'500.0',"[('Rated 4.0', 'RATED\n We ended up here on a...",[],Cafes,Banashankari

In [ ]:
df_explict= df.set_index("name")

In [ ]:
df_explict.columns

Index(['url', 'address', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [ ]:
df_explict.head()

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df_explict.loc['Jalsa']

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,804,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Paneer Lajawab, Masala Pa...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n Super ambience\nGreat...",[],Dine-out,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2/5,2173,+91 7406617555\r\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n A pretty decent place...",[],Delivery,Brookefield
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2 /5,2189,+91 7406617555\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n Friendly staff, avera...",[],Delivery,Marathahalli

In [ ]:
df_explict.loc['Suraaj']

KeyError: 'Suraaj'

In [ ]:
df_explict.reset_index(inplace=True)

In [ ]:
df_explict.head()

,name,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df_explict.columns

Index(['name', 'url', 'address', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [ ]:
df= df.rename(columns={'approx_cost(for two people)': 'cost_for_two','rate':'ratings'})

In [ ]:
df.head()

,url,address,name,online_order,book_table,ratings,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [ ]:
df['only_ratings']= df['ratings'].str[:-2] #more options

In [ ]:
df.head()

,url,address,name,online_order,book_table,ratings,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_ratings
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              23193 non-null  object
 1   address          23193 non-null  object
 2   name             23193 non-null  object
 3   online_order     23193 non-null  object
 4   book_table       23193 non-null  object
 5   ratings          23193 non-null  object
 6   votes            23193 non-null  int64
 7   phone            23193 non-null  object
 8   location         23193 non-null  object
 9   rest_type        23193 non-null  object
 10  dish_liked       23193 non-null  object
 11  cuisines         23193 non-null  object
 12  cost_for_two     23193 non-null  object
 13  reviews_list     23193 non-null  object
 14  menu_item        23193 non-null  object
 15  listed_in(type)  23193 non-null  object
 16  listed_in(city)  23193 non-null  object
 17  only_ratings     23193 non-null  object
dtypes: int64(1), object(17)
memory usage: 3.2+ MB

In [ ]:
df['only_ratings']= df['only_ratings'].astype(float)

ValueError: could not convert string to float: 'N'

In [ ]:
df['only_ratings'].replace('N','0.0',inplace=True)

In [ ]:
df['only_ratings']= df['only_ratings'].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              23193 non-null  object
 1   address          23193 non-null  object
 2   name             23193 non-null  object
 3   online_order     23193 non-null  object
 4   book_table       23193 non-null  object
 5   ratings          23193 non-null  object
 6   votes            23193 non-null  int64
 7   phone            23193 non-null  object
 8   location         23193 non-null  object
 9   rest_type        23193 non-null  object
 10  dish_liked       23193 non-null  object
 11  cuisines         23193 non-null  object
 12  cost_for_two     23193 non-null  object
 13  reviews_list     23193 non-null  object
 14  menu_item        23193 non-null  object
 15  listed_in(type)  23193 non-null  object
 16  listed_in(city)  23193 non-null  object
 17  only_ratings     23193 non-null  float64
dtypes: float64(1), int64(1), object(16)
memory usage: 3.2+ MB

In [ ]:
####
###Another version of Zomato's Dataset

!gdown 1YBEwvF07zaNNqW8sMPrwmgl4s73EPU_S

Downloading...
From (original): https://drive.google.com/uc?id=1YBEwvF07zaNNqW8sMPrwmgl4s73EPU_S
From (redirected): https://drive.google.com/uc?id=1YBEwvF07zaNNqW8sMPrwmgl4s73EPU_S&confirm=t&uuid=e67df8e6-c540-41c9-aaa1-13d06e2d9a98
To: /content/data.csv
100% 486M/486M [00:06<00:00, 76.4MB/s]

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False

In [ ]:
## 1. Finding unique values in the 'location' column
## 2. Count the unique values in 'location column
##3. Find the occurance of each unique value in the location column

In [ ]:
df['location'].unique()

array(['Banashankari', 'Basavanagudi', 'Jayanagar', 'Kumaraswamy Layout',
       'Rajarajeshwari Nagar', 'Mysore Road', 'Uttarahalli',
       'South Bangalore', 'Vijay Nagar', 'Bannerghatta Road', 'JP Nagar',
       'BTM', 'Wilson Garden', 'Koramangala 5th Block', 'Shanti Nagar',
       'Richmond Road', 'City Market', 'Bellandur', 'Sarjapur Road',
       'Marathahalli', 'HSR', 'Old Airport Road', 'Indiranagar',
       'Koramangala 1st Block', 'East Bangalore', 'MG Road',
       'Brigade Road', 'Lavelle Road', 'Church Street', 'Ulsoor',
       'Residency Road', 'Shivajinagar', 'Infantry Road',
       'St. Marks Road', 'Cunningham Road', 'Race Course Road', 'Domlur',
       'Koramangala 8th Block', 'Frazer Town', 'Ejipura', 'Vasanth Nagar',
       'Jeevan Bhima Nagar', 'Old Madras Road', 'Commercial Street',
       'Koramangala 6th Block', 'Majestic', 'Langford Town',
       'Koramangala 7th Block', 'Brookefield', 'Whitefield',
       'ITPL Main Road, Whitefield', 'Varthur Main Road, Whitefield',
       'Koramangala 2nd Block', 'Koramangala 3rd Block',
       'Koramangala 4th Block', 'Koramangala', 'Bommanahalli',
       'Hosur Road', 'Seshadripuram', 'Electronic City', 'Banaswadi',
       'North Bangalore', 'RT Nagar', 'Kammanahalli', 'Hennur',
       'HBR Layout', 'Kalyan Nagar', 'Thippasandra', 'CV Raman Nagar',
       'Kaggadasapura', 'Kanakapura Road', 'Nagawara', 'Rammurthy Nagar',
       'Sankey Road', 'Central Bangalore', 'Malleshwaram',
       'Sadashiv Nagar', 'Basaveshwara Nagar', 'Rajajinagar',
       'New BEL Road', 'West Bangalore', 'Yeshwantpur', 'Sanjay Nagar',
       'Sahakara Nagar', 'Jalahalli', 'Yelahanka', 'Magadi Road',
       'KR Puram'], dtype=object)

In [ ]:
df['location'].nunique()

88

In [ ]:
df['location'].value_counts()

location
Koramangala 5th Block    1783
BTM                      1456
Indiranagar              1350
HSR                      1162
Jayanagar                1037
                         ...
Kanakapura Road             2
West Bangalore              2
Yelahanka                   2
Magadi Road                 2
KR Puram                    1
Name: count, Length: 88, dtype: int64

In [ ]:
## Select the last two rows and the last column
df.iloc[-2:, -1 ]

23191    False
23192     True
Name: is_good, dtype: bool

In [ ]:
df.iloc[-2:, -1: ]

       is_good
23191    False
23192     True

In [ ]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

sample_df = pd.DataFrame(data)

In [ ]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R4     80     4.0

In [ ]:
sample_df.iloc[1:3, 1:3]=[[300,4.7],[200,3.7]]

In [ ]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    200     3.7
3         R4     80     4.0

In [ ]:
#misc but very useful
sample_df= sample_df.set_index('Restaurant')

In [ ]:
sample_df.loc['R2']

Votes     300.0
Rating      4.7
Name: R2, dtype: float64

In [ ]:
sample_df

            Votes  Rating
Restaurant
R1            120     4.1
R2            300     4.7
R3            200     3.7
R4             80     4.0

In [ ]:
sample_df.loc['R2','Votes']=200

In [ ]:
sample_df

            Votes  Rating
Restaurant
R1            120     4.1
R2            200     4.7
R3            200     3.7
R4             80     4.0

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

new_df = pd.DataFrame(data)

In [ ]:
demo_df=new_df.set_index('Restaurant')

In [ ]:
demo_df.loc['R2', 'Votes']= 200

In [ ]:
demo_df

            Votes  Rating
Restaurant
R1            120     4.1
R2            200     4.5
R3            150     3.9
R4             80     4.0

In [ ]:
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

final_df = pd.DataFrame(data)

In [ ]:
final_df.loc[final_df['Restaurant']=='R2','Votes']= 200

In [ ]:
final_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    200     4.5
2         R3    150     3.9
3         R4     80     4.0

In [ ]:
#3-4 questions in detailed notes

In [ ]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
sample_df.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
sample_df[sample_df.duplicated()]

  Restaurant  Votes  Rating
3         R2    240     4.5
5         R1    120     4.1

In [ ]:
new_df= sample_df.drop_duplicates()

In [ ]:
new_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
#HW-->>>> keep='first', keep=False

In [ ]:
sample_df['Restaurant'].drop_duplicates()

0    R1
1    R2
2    R3
4    R4
Name: Restaurant, dtype: object

In [ ]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
sample_df['Rating'].sum()

np.float64(25.1)

In [ ]:
sample_df['Rating'].mean()

np.float64(4.183333333333334)

In [ ]:
sample_df['Rating'].agg(['sum','mean','min','max'])

sum     25.100000
mean     4.183333
min      3.900000
max      4.500000
Name: Rating, dtype: float64

In [ ]:
sample_df['Rating'].describe()

count    6.000000
mean     4.183333
std      0.256255
min      3.900000
25%      4.025000
50%      4.100000
75%      4.400000
max      4.500000
Name: Rating, dtype: float64

In [ ]:
sample_df.describe()

            Votes    Rating
count    6.000000  6.000000
mean   158.333333  4.183333
std     67.057190  0.256255
min     80.000000  3.900000
25%    120.000000  4.025000
50%    135.000000  4.100000
75%    217.500000  4.400000
max    240.000000  4.500000

In [ ]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
sample_df.sort_values(by='Votes', ascending=True)

  Restaurant  Votes  Rating
4         R4     80     4.0
0         R1    120     4.1
5         R1    120     4.1
2         R3    150     3.9
3         R2    240     4.5
1         R2    240     4.5

In [ ]:
sample_df.sort_values(by='Votes', ascending=False)

  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0

In [ ]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R7", "R4", "R8"],
    "Votes": [120, 240, 150, 241, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.2]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R7    241     4.5
4         R4     80     4.0
5         R8    120     4.2

In [ ]:
sample_df.sort_values(by=['Votes','Rating'], ascending=[False,False])

  Restaurant  Votes  Rating
3         R7    241     4.5
1         R2    240     4.5
2         R3    150     3.9
5         R8    120     4.2
0         R1    120     4.1
4         R4     80     4.0